server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atl_academy_security
    username: postgres
    password: 2000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format-sql: true
    open-in-view: true

